spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/garson_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Allow cross origin for local dev
server.port=8081
